### ISSUE TITLE
I'm using laravel 8.x and i followed all instructions 

### ISSUE THREAD

**Issue by KBM90** [laravel-frontend-presets/black-dashboard#14] opened 2021-06-17 14:10 UTC
InvalidArgumentException

  Invalid preset.

  at C:\xampp\htdocs\stamp\vendor\laravel\ui\src\UiCommand.php:41
     37▕             return call_user_func(static::$macros[$this->argument('type')], $this);
     38▕         }
     39▕
     40▕         if (! in_array($this->argument('type'), ['bootstrap', 'vue', 'react'])) {
  ➜  41▕             throw new InvalidArgumentException('Invalid preset.');
     42▕         }
     43▕
     44▕         $this->{$this->argument('type')}();
     45▕

  1   C:\xampp\htdocs\stamp\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
      Laravel\Ui\UiCommand::handle()

  2   C:\xampp\htdocs\stamp\vendor\laravel\framework\src\Illuminate\Container\Util.php:40
      Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()

**Comment by teamupdivision** [comment] 2021-07-22 13:40
Hi @KBM90,

Thank you for reporting this issue and sorry for the delay.
 
Could you please send a few more details to us (prerequisites, Expected Behavior, Current Behavior, Steps and Context)?  Also, if you can send to us a screenshot or video recording with the steps, it will help a lot in investigating this further.
 
All the best,
UPDIVISION Team

**Comment by teamupdivision** [comment] 2021-08-23 12:35
Hi there @KBM90,

We would like to check if the issue was solved or if you can share a few more details on the steps followed. Please let us know if there is anything else we can help with and if you have any other issues.

Best,
Updivision

**Comment by KBM90** [comment] 2021-08-23 12:38
Hi ,
No i didn't solve it , so i switched to material design dashboard .

**Comment by teamupdivision** [comment] 2021-08-27 06:30
Hi @KBM90,

We did a new check, but we were not able to reproduce the error. Could you please help us with a few more details on Prerequisites, Expected Behavior, Current Behavior, Steps and Context, it will help a lot. A video/capture with the steps would be also really helpful.

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment] 2021-10-06 07:58
Hi @KBM90,

Hope there are no other issues on this one. We will go ahead and close this ticket. If there is anything else we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).

**Closed as completed** 2021-10-06 07:58 UTC
